server:
  port: 8100
datasource:
  db-hero-app:
    jdbcUrl: jdbc:mysql://ddd-herodb.cc1lweskpg39.ap-northeast-2.rds.amazonaws.com:3306/HERO?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: hero
    password: dddhero19
    driverClassName: com.mysql.cj.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    max-active: 1